CREATE TABLE
  public.reservas (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    checkin timestamp(6) without time zone NOT NULL,
    checkout timestamp(6) without time zone NOT NULL,
    created_at timestamp(6) without time zone NULL,
    documento character varying(255) NOT NULL,
    nome character varying(255) NOT NULL,
    valor_reserva double precision NOT NULL
  );

ALTER TABLE
  public.reservas
ADD
  CONSTRAINT reservas_pkey PRIMARY KEY (id)






