CREATE TABLE
  public.pagamentos (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    data_pagamento timestamp(6) without time zone NOT NULL,
    parcela integer NOT NULL,
    reserva_id bigint NULL,
    valor_pagamento double precision NOT NULL
  );

ALTER TABLE
  public.pagamentos
ADD
  CONSTRAINT pagamentos_pkey PRIMARY KEY (id)