CREATE TABLE
  public.usuarios (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    login character varying(100) NOT NULL,
    senha character varying(255) NOT NULL
  );

  ALTER TABLE
    public.usuarios
  ADD
    CONSTRAINT usuarios_pkey PRIMARY KEY (id)


